### ISSUE TITLE
正在翻译 se05- ch14

### ISSUE THREAD

**Issue by Crowds21** [Angus-Liu/Atomic-Kotlin-zh#4]
正在翻译该章节,提个 issue 认领一下, 防止和其他人冲突.

**Comment by Angus-Liu** [comment]
已合并修改，幸苦了。若后续需要修改或者翻译，可以继续提 PR 和 issue 哈。

**Comment by Crowds21** [comment]
> 已合并修改，幸苦了。若后续需要修改或者翻译，可以继续提 PR 和 issue 哈。

好的 :smile:
